### ISSUE TITLE
Inconsistent numbering/missing spaces

### ISSUE THREAD

**Issue by mabam** [ekalinin/SpaceName#4]
Thanks for your work on this! I’m happy to have found something that doesn’t require me to disable SIP like MacForge with the Spaces Renamer plugin does.

However, I’m having some issues:
- While in Mission Control spaces are named “Desktop 1”, “Desktop 2”, …, with consecutive numbering, I found that in SpaceName numbering is inconsistent. It can change after setting a name and through restarts of the machine, resulting in disappearance of set names or linking them to the wrong space.
- Also, while having multiple spaces in Mission Control, SpaceName often shows only one or a few of the existing spaces.

Not sure whether that’s related, but I’m on a multi screen setup (three monitors).

**Comment by ekalinin** [comment]
Hey!

Thanks for report!

> While in Mission Control spaces are named “Desktop 1”, “Desktop 2”, …, with consecutive numbering, I found that in SpaceName numbering is inconsistent. It can change after setting a name and through restarts of the machine, resulting in disappearance of set names or linking them to the wrong space.

Can I ask you to show me a screenshot of the problem?
As I used auto increment number for each space id, therefore, the numbering should be consistent:
- https://github.com/ekalinin/SpaceName/blob/0.5/init.lua#L89

> Also, while having multiple spaces in Mission Control, SpaceName often shows only one or a few of the existing spaces.

Do you have the option "Displays have separate Spaces" enabled? (System Preferences → Mission Control)
I'm using one external monitor and "Displays have separate Spaces" is disabled and all spaces are in place :)

**Comment by mabam** [comment]
> Do you have the option "Displays have separate Spaces" enabled? (System Preferences → Mission Control)

Yes, I need that for my workflow.

> Can I ask you to show me a screenshot of the problem?

- The first screenshot shows two spaces in SpaceName numbered 5 and 2 (which is the same in SpaceName on every screen):
![Bildschirmfoto 2023-11-20 um 00 24 51 (2)](https://github.com/ekalinin/SpaceName/assets/11489153/7cd7ad2a-6857-473c-bf01-4f97180286d1)

- This second shot shows all spaces available for the third screen in Mission Control, which is 4 in total numbered 3 through 6.
![Bildschirmfoto 2023-11-20 um 00 25 02 (2)](https://github.com/ekalinin/SpaceName/assets/11489153/752d7c15-c57d-455c-b9fe-16510ced0f7b)
In Mission Control, numbers 1 and 2 belong to my other two screens.

**Comment by ekalinin** [comment]
Hey,

Please, try a new version:
- https://github.com/ekalinin/SpaceName/releases/tag/0.6

**Comment by ekalinin** [comment]
Should be fixed now.
